root = "."
tmp_dir = "tmp"

[build]
  working_dir = "."
  cmd = "go build -o tmp/log_processor.exe ."
  bin = "tmp/log_processor.exe"
  env = [
    "RABBITMQ_SERVER_URL=amqp://guest:guest@localhost:5672/",
    "DATABASE_URL=\"host=localhost port=5433 user=postgres password=postgres dbname=sentinelsync sslmode=disable\""
  ]
  stop_on_error = true
  log = "air_build.log"

[run]
  cmd = "tmp/log_processor.exe"
  log = "air_run.log"

[misc]
  clean_on_exit = true
